-- ===== 투쟁기금 단숨에 1.5억 모았다…'공룡 경찰' 3대 모임 해부 =====
INSERT INTO questions (news_id, content, question_format, choices, answer, explanation, hint, game_mode, main_category, sub_category, level) VALUES
                                                                                                                                                 ((SELECT news_id FROM news_articles WHERE title = '투쟁기금 단숨에 1.5억 모았다…''공룡 경찰'' 3대 모임 해부'), '다음 문장에서 밑줄 친 ''카르텔''의 문맥적 의미로 가장 적절한 것은?
(이 조직 내부에는 출신 대학과 입직 경로에 따라 서로 밀어주고 끌어주는 카르텔이 존재한다.)', 'multiple_choice'::question_format_type, '["자유로운 경쟁을 통한 시장 질서", "특정 집단이 서로 밀어주고 끌어주며 이익을 나누는 결탁 구조", "국가가 법으로 정한 공식 조직", "폭력을 동반하는 범죄 조직"]', '특정 집단이 서로 밀어주고 끌어주며 이익을 나누는 결탁 구조', '기사에서 ''카르텔''은 출신 대학·입직 경로에 따라 서로 밀어주고 끌어주는 비공식적 결탁 구조를 가리키는 말로 쓰였다.', '바로 앞뒤 문장에서 카르텔이 어떻게 설명되는지 살펴보세요.', 'daily_solo'::game_mode_type, 'vocab'::main_category_type, 'vocab_meaning'::sub_category_type, 4),
                                                                                                                                                 ((SELECT news_id FROM news_articles WHERE title = '투쟁기금 단숨에 1.5억 모았다…''공룡 경찰'' 3대 모임 해부'), '다음 문장에서 밑줄 친 표현을 바꿔 써도 문맥상 어색하지 않은 것은?
(전국 13만 4000명에 달하는 경찰 조직이 술렁이고 있다.)', 'multiple_choice'::question_format_type, '["동요하고 있다", "침묵하고 있다", "해체되고 있다", "승진하고 있다"]', '동요하고 있다', '''술렁이다''는 어수선하게 흔들리는 분위기를 뜻하므로 ''동요하다''로 바꿔도 의미가 통한다.', '''술렁이다''는 조용하지 않고 어수선한 상태를 뜻해요.', 'daily_solo'::game_mode_type, 'vocab'::main_category_type, 'vocab_appropriateness'::sub_category_type, 4),
                                                                                                                                                 ((SELECT news_id FROM news_articles WHERE title = '투쟁기금 단숨에 1.5억 모았다…''공룡 경찰'' 3대 모임 해부'), '10월 2일 개정 형사소송법이 시행되면 검사의 수사권이 사라지고 경찰이 사건 수사의 중심에 서게 된다.', 'OX'::question_format_type, '["O", "X"]', 'O', '기사에 ''10월 2일 개정 형사소송법 시행으로 검사의 수사권이 사라지고 경찰이 사건 수사의 중심에 서게 되기 때문''이라고 명시돼 있다.', '형사소송법 개정과 관련된 문단을 다시 확인해보세요.', 'daily_solo'::game_mode_type, 'info_extraction'::main_category_type, 'info_consistency'::sub_category_type, 4),
                                                                                                                                                 ((SELECT news_id FROM news_articles WHERE title = '투쟁기금 단숨에 1.5억 모았다…''공룡 경찰'' 3대 모임 해부'), '경찰 조직 내부에 출신별 카르텔이 존재한다는 주장을 뒷받침하는 근거로 가장 적절한 것은?', 'multiple_choice'::question_format_type, '["경찰대 출신이 고위직 절반 이상을 차지하고 동국대·고시 특채 출신이 이를 견제한다는 서술", "전국 경찰이 13만 4000명에 달한다는 서술", "여성 경찰 모임이 11월에 별도 행사를 연다는 서술", "형사소송법이 10월 2일 개정 시행된다는 서술"]', '경찰대 출신이 고위직 절반 이상을 차지하고 동국대·고시 특채 출신이 이를 견제한다는 서술', '이 서술이 출신·입직 경로에 따른 카르텔 구조를 직접적으로 뒷받침하는 근거다.', '''카르텔''을 설명하는 문장 바로 앞뒤를 보세요.', 'daily_solo'::game_mode_type, 'info_extraction'::main_category_type, 'info_evidence'::sub_category_type, 4),
                                                                                                                                                 ((SELECT news_id FROM news_articles WHERE title = '투쟁기금 단숨에 1.5억 모았다…''공룡 경찰'' 3대 모임 해부'), '이 글이 다루는 중심 소재로 가장 적절한 것은?', 'multiple_choice'::question_format_type, '["경찰 조직 내 여러 모임의 형성 배경과 성격 차이", "국회의원 선거 결과 분석", "검찰과 경찰의 예산 비교", "경찰대학교 입시 제도 개편"]', '경찰 조직 내 여러 모임의 형성 배경과 성격 차이', '기사는 전국경찰직장협의회, 폴네티앙, 경찰젠더연구회 등 경찰 내 여러 모임이 왜 따로 결성됐는지를 다룬다.', '기사에 등장하는 세 모임의 이름을 떠올려 보세요.', 'daily_solo'::game_mode_type, 'core_understanding'::main_category_type, 'core_topic'::sub_category_type, 4),
                                                                                                                                                 ((SELECT news_id FROM news_articles WHERE title = '투쟁기금 단숨에 1.5억 모았다…''공룡 경찰'' 3대 모임 해부'), '취재팀이 이 기사를 통해 최종적으로 확인하려 한 것이 무엇인지 한 문장으로 서술하시오.', 'short_answer'::question_format_type, NULL, '전국경찰직장협의회, 폴네티앙 등 경찰 내 모임들이 어떻게 만들어졌고 어떤 자금으로 운영되는지, 그리고 이들 모임이 특정 정치 세력과 연결됐다는 의혹이 사실인지 확인하려 했다.', '마지막 문단에서 취재팀의 취재 목적이 직접 서술돼 있다.', '기사의 마지막 문단을 다시 읽어보세요.', 'daily_solo'::game_mode_type, 'core_understanding'::main_category_type, 'core_gist'::sub_category_type, 4),
                                                                                                                                                 ((SELECT news_id FROM news_articles WHERE title = '투쟁기금 단숨에 1.5억 모았다…''공룡 경찰'' 3대 모임 해부'), '경찰 조직 내에 출신 대학·입직 경로에 따른 카르텔이 존재한다는 서술을 통해 추론할 수 있는 내용으로 가장 적절한 것은?', 'multiple_choice'::question_format_type, '["경찰 조직의 인사·승진에서 출신에 따른 유불리가 존재할 수 있다", "모든 경찰관은 동일한 대학 출신이다", "경찰 조직에는 어떠한 내부 갈등도 없다", "형사소송법 개정은 경찰 조직과 무관하다"]', '경찰 조직의 인사·승진에서 출신에 따른 유불리가 존재할 수 있다', '특정 출신이 고위직을 차지하고 다른 출신이 이를 견제한다는 서술은 인사상 유불리 구조를 암시한다.', '''견제 세력으로 자리 잡고 있다''는 표현이 무엇을 시사하는지 생각해보세요.', 'daily_solo'::game_mode_type, 'inference_judgment'::main_category_type, 'inference_implication'::sub_category_type, 4),
                                                                                                                                                 ((SELECT news_id FROM news_articles WHERE title = '투쟁기금 단숨에 1.5억 모았다…''공룡 경찰'' 3대 모임 해부'), '이 기사 다음에 이어질 내용으로 가장 자연스러운 것은?', 'multiple_choice'::question_format_type, '["전국경찰직장협의회와 폴네티앙의 결성 배경, 구성원 수, 자금 출처에 대한 구체적인 취재 내용", "경찰청장의 사임 발표", "경찰 시험 과목 개편안 발표", "경찰차 디자인 변경 소식"]', '전국경찰직장협의회와 폴네티앙의 결성 배경, 구성원 수, 자금 출처에 대한 구체적인 취재 내용', '마지막 문단에서 취재팀이 이 조직들의 결성 과정과 자금, 의혹의 사실 여부를 확인하겠다고 예고했다.', '마지막 문단에서 취재팀이 무엇을 확인하겠다고 했는지 보세요.', 'daily_solo'::game_mode_type, 'inference_judgment'::main_category_type, 'inference_continuation'::sub_category_type, 4),
                                                                                                                                                 ((SELECT news_id FROM news_articles WHERE title = '투쟁기금 단숨에 1.5억 모았다…''공룡 경찰'' 3대 모임 해부'), '다음 중 이 기사의 흐름과 관련 없는 문장은?
① 최근 장윤기 사건과 제주 실종 사건을 계기로 경찰 개혁 요구가 커졌다.
② 10월 2일 개정 형사소송법 시행으로 경찰이 수사의 중심에 선다.
③ 국내 커피 프랜차이즈 매출이 지난달 큰 폭으로 증가했다.
④ 국회에서 경찰 관련 토론회가 이틀 연속 열렸다.', 'multiple_choice'::question_format_type, '["①", "②", "③", "④"]', '③', '커피 프랜차이즈 매출과 관련된 내용은 경찰 조직 개편을 다루는 이 기사의 흐름과 관련이 없다.', '경찰 조직과 직접 관련이 없는 문장을 찾아보세요.', 'daily_solo'::game_mode_type, 'structure'::main_category_type, 'structure_irrelevant_sentence'::sub_category_type, 4),
                                                                                                                                                 ((SELECT news_id FROM news_articles WHERE title = '투쟁기금 단숨에 1.5억 모았다…''공룡 경찰'' 3대 모임 해부'), '다음 문장이 들어가기에 가장 적절한 위치를 고르시오.
[삽입 문장] "이런 출신별 카르텔과는 별개로, 여러 출신과 계급이 뒤섞여 활동하는 모임들도 있다."
(가) 최근 장윤기 사건과 제주 실종 사건을 계기로 경찰 개혁 요구가 커졌다. (나) 경찰대 출신이 고위직 절반 이상을 차지하고 동국대·고시 특채 출신이 견제 세력으로 자리 잡고 있다. (다) 전국경찰직장협의회, 폴네티앙, 경찰젠더연구회가 그것이다. (라) 취재팀은 이들 조직의 결성 배경과 자금, 의혹을 확인하고자 했다.', 'multiple_choice'::question_format_type, '["(가)", "(나)", "(다)", "(라)"]', '(나)', '''이런 출신별 카르텔과는 별개로''라는 문구는 카르텔을 설명한 문장(나) 바로 다음, 여러 모임을 나열하는 문장(다) 바로 앞에 와야 자연스럽다.', '''이런 출신별 카르텔과는 별개로''라는 표현이 어떤 내용 다음에 와야 자연스러운지 생각해보세요.', 'daily_solo'::game_mode_type, 'structure'::main_category_type, 'structure_sentence_insertion'::sub_category_type, 4),
                                                                                                                                                 ((SELECT news_id FROM news_articles WHERE title = '투쟁기금 단숨에 1.5억 모았다…''공룡 경찰'' 3대 모임 해부'), '[문단] 이 조직 내부에는 출신 대학과 입직 경로에 따라 서로 밀어주고 끌어주는 카르텔이 존재한다. 경찰대 출신이 고위직 절반 이상을 차지하고, 동국대 경찰행정학과 출신과 고시 특채 출신이 이를 견제하는 세력으로 자리 잡고 있는 구조다.
 
[문제] 윗글에서 ''특정 집단이 서로 밀어주고 끌어주며 이익을 나누는 결탁 구조''를 뜻하는 단어를 찾아 한 단어로 쓰시오.', 'short_answer'::question_format_type, NULL, '카르텔', '윗글에서 ''카르텔''은 출신 대학과 입직 경로에 따라 서로 밀어주고 끌어주는 결탁 구조를 가리키는 말로 쓰였다.', '외래어로 된 한 단어입니다.', 'room'::game_mode_type, 'vocab'::main_category_type, 'vocab_meaning'::sub_category_type, 4),
                                                                                                                                                 ((SELECT news_id FROM news_articles WHERE title = '투쟁기금 단숨에 1.5억 모았다…''공룡 경찰'' 3대 모임 해부'), '[문단] 전국 13만 4000명에 달하는 경찰 조직이 술렁이고 있다. 최근 장윤기 사건과 제주 실종 사건을 계기로 경찰 개혁을 요구하는 목소리가 커진 데다, 10월 2일 개정 형사소송법 시행으로 검사의 수사권이 사라지고 경찰이 사건 수사의 중심에 서게 되기 때문이다.
 
[문제] ''술렁이고 있다''를 다른 말로 바꿔 쓸 때 가장 자연스러운 것은?', 'multiple_choice'::question_format_type, '["어수선하게 동요하고 있다", "완전히 안정되어 있다", "조용히 해산하고 있다", "빠르게 성장하고 있다"]', '어수선하게 동요하고 있다', '''술렁이다''는 어수선하게 흔들리는 분위기를 뜻한다.', '''술렁이다''가 긍정적 상태인지 어수선한 상태인지 생각해보세요.', 'room'::game_mode_type, 'vocab'::main_category_type, 'vocab_paraphrase'::sub_category_type, 4),
                                                                                                                                                 ((SELECT news_id FROM news_articles WHERE title = '투쟁기금 단숨에 1.5억 모았다…''공룡 경찰'' 3대 모임 해부'), '[문단] 전국 13만 4000명에 달하는 경찰 조직이 술렁이고 있다. 최근 장윤기 사건과 제주 실종 사건을 계기로 경찰 개혁을 요구하는 목소리가 커진 데다, 10월 2일 개정 형사소송법 시행으로 검사의 수사권이 사라지고 경찰이 사건 수사의 중심에 서게 되기 때문이다.
 
[문제] 윗글에 따르면 10월 2일 개정 형사소송법이 시행되면 검사의 수사권이 사라진다.', 'OX'::question_format_type, '["O", "X"]', 'O', '윗글에 이 내용이 그대로 명시돼 있다.', '형사소송법과 관련된 문장을 다시 확인해보세요.', 'room'::game_mode_type, 'info_extraction'::main_category_type, 'info_consistency'::sub_category_type, 4),
                                                                                                                                                 ((SELECT news_id FROM news_articles WHERE title = '투쟁기금 단숨에 1.5억 모았다…''공룡 경찰'' 3대 모임 해부'), '[문단] 이런 출신별 카르텔과는 별개로, 여러 출신과 계급이 뒤섞여 활동하는 모임들도 있다. 전국경찰직장협의회, 폴네티앙, 경찰젠더연구회가 그것이다.
 
[문제] 윗글에서 출신별 카르텔과 별개로 존재하는 모임의 예로 제시된 것은?', 'multiple_choice'::question_format_type, '["전국경찰직장협의회, 폴네티앙, 경찰젠더연구회", "대한변호사협회, 한국기자협회", "전국공무원노동조합, 교원단체총연합회", "한국경영자총협회, 중소기업중앙회"]', '전국경찰직장협의회, 폴네티앙, 경찰젠더연구회', '윗글에서 세 모임의 이름을 직접 나열하고 있다.', '윗글에서 모임 이름이 나온 문장을 확인해보세요.', 'room'::game_mode_type, 'info_extraction'::main_category_type, 'info_evidence'::sub_category_type, 4),
                                                                                                                                                 ((SELECT news_id FROM news_articles WHERE title = '투쟁기금 단숨에 1.5억 모았다…''공룡 경찰'' 3대 모임 해부'), '[문단] 이런 분위기를 반영하듯 국회에서는 9월 6일과 7일 이틀 연속으로 경찰 관련 토론회가 열렸다. 6일 행사는 전국경찰직장협의회가 조국혁신당 정춘생 의원과 함께, 7일 행사는 폴네티앙이 조국혁신당 황운하 의원, 인권연대와 함께 주최했다.
 
[문제] 윗글이 다루는 중심 소재로 가장 적절한 것은?', 'multiple_choice'::question_format_type, '["경찰 조직 내 여러 모임과 그 활동", "국회의원 선거 일정", "경찰 예산 편성 절차", "경찰대학 입시 제도"]', '경찰 조직 내 여러 모임과 그 활동', '윗글은 전국경찰직장협의회와 폴네티앙이 각각 개최한 토론회를 설명하고 있다.', '윗글에 나온 단체 이름들을 확인해보세요.', 'room'::game_mode_type, 'core_understanding'::main_category_type, 'core_topic'::sub_category_type, 4),
                                                                                                                                                 ((SELECT news_id FROM news_articles WHERE title = '투쟁기금 단숨에 1.5억 모았다…''공룡 경찰'' 3대 모임 해부'), '[문단] 지난 6일 일요일 오후 2시, 서울 여의도 국회의원회관에는 삭발을 한 이들을 포함해 경찰 150여 명이 하나둘 모여들었다.
 
[문제] 윗글에 어울리는 제목으로 가장 적절한 것은?', 'multiple_choice'::question_format_type, '["경찰 조직, 잇따른 토론회로 술렁이다", "경찰청, 신입 경찰 채용 확대 발표", "경찰차 디자인 전면 교체", "경찰 정년 연장 법안 통과"]', '경찰 조직, 잇따른 토론회로 술렁이다', '윗글은 경찰들이 모여 토론회와 행사를 여는 모습을 보여준다.', '윗글에서 어떤 사람들이 왜 모였는지 생각해보세요.', 'room'::game_mode_type, 'core_understanding'::main_category_type, 'core_title'::sub_category_type, 4),
                                                                                                                                                 ((SELECT news_id FROM news_articles WHERE title = '투쟁기금 단숨에 1.5억 모았다…''공룡 경찰'' 3대 모임 해부'), '[문단] 이 조직 내부에는 출신 대학과 입직 경로에 따라 서로 밀어주고 끌어주는 카르텔이 존재한다. 경찰대 출신이 고위직 절반 이상을 차지하고, 동국대 경찰행정학과 출신과 고시 특채 출신이 이를 견제하는 세력으로 자리 잡고 있는 구조다.
 
[문제] 윗글을 통해 알 수 있는 사실로 가장 적절한 것은?', 'multiple_choice'::question_format_type, '["경찰 조직의 인사에서 출신에 따른 차이가 존재할 수 있다", "모든 경찰관은 같은 대학 출신이다", "경찰 조직에는 어떠한 갈등도 없다", "경찰대학은 최근 폐지되었다"]', '경찰 조직의 인사에서 출신에 따른 차이가 존재할 수 있다', '특정 출신이 고위직을 차지하고 다른 출신이 이를 견제한다는 내용은 인사상 차이를 암시한다.', '''고위직 절반 이상을 차지''라는 표현이 무엇을 뜻하는지 생각해보세요.', 'room'::game_mode_type, 'inference_judgment'::main_category_type, 'inference_implication'::sub_category_type, 4),
                                                                                                                                                 ((SELECT news_id FROM news_articles WHERE title = '투쟁기금 단숨에 1.5억 모았다…''공룡 경찰'' 3대 모임 해부'), '[문단] 취재팀은 이들 조직이 어떻게 만들어졌는지, 몇 명이 어떤 자금으로 활동하는지, 그리고 보수 진영 일각에서 제기해온 "경찰직장협의회가 민주노총과 연결된 강경조직"이라거나 "폴네티앙 일부가 친노 세력과 연결돼 정치화·비밀결사화됐다"는 의혹이 사실인지를 확인하고자 했다.
 
[문제] 윗글 다음에 이어질 내용으로 가장 자연스러운 것은?', 'multiple_choice'::question_format_type, '["각 모임의 결성 배경과 자금 출처에 대한 구체적인 취재 내용", "경찰청장의 임기 만료 소식", "경찰 시험 일정 변경 공지", "경찰 유니폼 디자인 변경 소식"]', '각 모임의 결성 배경과 자금 출처에 대한 구체적인 취재 내용', '윗글에서 취재팀이 확인하고자 한 내용이 무엇인지 예고하고 있다.', '윗글에서 취재팀이 무엇을 확인하려 했는지 확인해보세요.', 'room'::game_mode_type, 'inference_judgment'::main_category_type, 'inference_continuation'::sub_category_type, 4),
                                                                                                                                                 ((SELECT news_id FROM news_articles WHERE title = '투쟁기금 단숨에 1.5억 모았다…''공룡 경찰'' 3대 모임 해부'), '[문단] 이런 분위기를 반영하듯 국회에서는 9월 6일과 7일 이틀 연속으로 경찰 관련 토론회가 열렸다. 6일 행사는 전국경찰직장협의회가 조국혁신당 정춘생 의원과 함께, 7일 행사는 폴네티앙이 조국혁신당 황운하 의원, 인권연대와 함께 주최했다.
 
[문제] 윗글에 언급된 두 행사를 열린 순서대로 나열한 것은?', 'multiple_choice'::question_format_type, '["전국경찰직장협의회 주최 행사 → 폴네티앙 주최 행사", "폴네티앙 주최 행사 → 전국경찰직장협의회 주최 행사", "경찰젠더연구회 행사 → 전국경찰직장협의회 행사", "폴네티앙 주최 행사 → 경찰젠더연구회 행사"]', '전국경찰직장협의회 주최 행사 → 폴네티앙 주최 행사', '윗글에서 6일 전국경찰직장협의회 행사, 7일 폴네티앙 행사 순서로 열렸다고 설명한다.', '윗글에서 날짜와 단체 이름을 짝지어 확인해보세요.', 'room'::game_mode_type, 'structure'::main_category_type, 'structure_order'::sub_category_type, 4),
                                                                                                                                                 ((SELECT news_id FROM news_articles WHERE title = '투쟁기금 단숨에 1.5억 모았다…''공룡 경찰'' 3대 모임 해부'), '[문단] 이 조직 내부에는 출신 대학과 입직 경로에 따라 서로 밀어주고 끌어주는 카르텔이 존재한다. 경찰대 출신이 고위직 절반 이상을 차지하고, 동국대 경찰행정학과 출신과 고시 특채 출신이 이를 견제하는 세력으로 자리 잡고 있는 구조다.
 
[문제] 다음 중 윗글의 흐름과 관계없는 문장은?', 'multiple_choice'::question_format_type, '["경찰 조직 내부에는 출신 대학과 입직 경로에 따른 카르텔이 존재한다.", "경찰대 출신이 고위직 절반 이상을 차지한다.", "이번 여름 전국 아이스크림 판매량이 크게 증가했다.", "동국대 출신과 고시 특채 출신이 견제 세력으로 자리잡고 있다."]', '이번 여름 전국 아이스크림 판매량이 크게 증가했다.', '윗글은 경찰 조직 내 카르텔 구조를 다루고 있으며, 아이스크림 판매량은 이와 관계없는 내용이다.', '윗글이 다루는 주제가 무엇인지 확인해보세요.', 'room'::game_mode_type, 'structure'::main_category_type, 'structure_irrelevant_sentence'::sub_category_type, 4);

-----------------
